{% set name = "horton" %}
{% set version = "2.3.5" %}

package:
  name: {{ name | lower }} 
  version: {{ version }}

source:
#  path: ../../horton/
  url: https://github.com/theochem/horton/archive/refs/tags/{{ version }}.tar.gz
  sha256: 40f0cc5a61e7a00b396d26be7dc4a69ac872697f6584ae3620e6908d6c070608 

build:
  number: 1
  skip: true  # [win]
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - numpy
    - cython
    - h5py
    - libxc
    - libint
  run:
    - python
    - numpy
    - scipy
    - h5py
    - matplotlib-base
    - libxc
    - libint
    - cython
test:
  source_files:
    - pytest.ini
  requires:
    - pytest
#    - conda-verify
  imports:
    - horton
  commands:
    - pytest --pyargs horton -vv
  
about:
  home: https://github.com/theochem/horton
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: "Helpful Open-source Research TOol for N-fermion systems"
  description: |
    HORTON is a Helpful Open-source Research TOol for N-fermion systems, written primarily in the Python programming language. 
    (HORTON is named after the helpful pachyderm, not the Canadian caffeine supply store.) The ultimate goal of HORTON is to 
    provide a platform for testing new ideas on the quantum many-body problem at a reasonable computational cost. Although HORTON 
    is primarily designed to be a quantum-chemistry program, it can perform computations involving model Hamiltonians, and could 
    be extended for computations in nuclear physics.
  doc_url: https://theochem.github.io/horton/
  dev_url: https://github.com/theochem/horton

extra:
  recipe-maintainers:
    - matt-chan
  
